Repository adityabisoi/startup-incubator, pull requests merged in 2022-04, with the labels that each got.

#57 confirmpasswordadded
  client/src/Register/Register.jsx
Labels: GSSoC22

#63 likes incremention added
  client/src/Components/Product/ProductPreview.jsx
  client/src/HomePage/Body.jsx
  client/src/utils/constants.js
Labels: GSSoC22, Level2

#58 userModelisAdded
  .eslintrc.json
  client/package-lock.json
  model/User.js
  package-lock.json
  package.json
Labels: GSSoC22, Level2

#67 Subject and favicon changed
  client/public/favicon.ico
  client/public/index.html
Labels: GSSoC22, Level1

#72 Signup option added in login page and vice versa
  client/src/HomePage/Header.jsx
  client/src/Login/Login.css
  client/src/Login/Login.jsx
  client/src/Register/Register.css
  client/src/Register/Register.jsx
Labels: GSSoC22, Level3

#81 Contact page added
  client/src/App.js
  client/src/ContactPage/Contact.css
  client/src/ContactPage/ContactPage.js
  client/src/HomePage/Header.jsx
Labels: GSSoC22, Level2

#82 New product getting saved to local storage
  client/src/CreateProduct/CreateProduct.jsx
Labels: GSSoC22

#70 Login/SignUp endpoints Created, Db set
  db/mongoose.js
  model/User.js
  package-lock.json
  package.json
  routes/user.js
  server.js
Labels: GSSoC22, Level3

#77 hover effect and click on card added
  client/src/Components/Product/ProductPreview.jsx
Labels: GSSoC22, Level2

#88 New product button working
  client/src/HomePage/Header.jsx
Labels: GSSoC22, Level1

#91 Home button added
  client/src/HomePage/Header.jsx
Labels: GSSoC22, Level2

#95 Scroll Button position and UI corrected
  client/src/App.css
  client/src/App.js
  client/src/Components/ScrollButton/ScrollButton.css
  client/src/Components/ScrollButton/ScrollButton.jsx
Labels: GSSoC22, Level2

#96 Products get sorted according to likes
  client/src/HomePage/Body.jsx
Labels: GSSoC22, Level2
