Repository adityabisoi/startup-incubator, pull requests merged in 2022-05, with the labels that each got.

#97 ConnectionEstablished
  .eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/Login/Login.jsx
  client/src/Register/Register.jsx
  db/mongoose.js
  package-lock.json
  package.json
  routes/user.js
  server.js
Labels: GSSoC22, Level2

#99 View more button added
  client/src/HomePage/Body.jsx
Labels: GSSoC22, Level3

#102 Add Comment functionality added
  client/src/Components/Product/CommentSection.jsx
  client/src/Components/Product/Product.jsx
  client/src/Components/Product/ProductPreview.jsx
Labels: GSSoC22, Level3

#104 ProjectSchemaAdded
  client/package-lock.json
  client/package.json
  model/Project.js
  package-lock.json
  package.json
  routes/project.js
  server.js
Labels: GSSoC22, Level3

#106 Authentication set
  client/src/App.js
  client/src/Components/Product/Product.jsx
  client/src/CreateProduct/CreateProduct.jsx
  client/src/HomePage/Navbar/Navbar.css
  client/src/HomePage/Navbar/Navbar.js
  client/src/Login/Login.jsx
  client/src/Register/Register.jsx
  db/mongoose.js
  middleware/auth.js
  model/User.js
  package-lock.json
  package.json
  routes/project.js
  routes/user.js
Labels: GSSoC22, Level3

#108 NavbarDynamic
  client/src/HomePage/Navbar/Navbar.js
Labels: GSSoC22, Level2

#118 SchemaMdoified
  model/Project.js
  routes/project.js
Labels: GSSoC22, Level2

#117 New Product button only visible after logging in
  client/package-lock.json
  client/src/HomePage/Navbar/Navbar.js
  package-lock.json
Labels: GSSoC22, Level2

#114 Home button added with proper UI
  client/src/HomePage/Navbar/Navbar.css
  client/src/HomePage/Navbar/Navbar.js
  routes/user.js
Labels: GSSoC22, Level2

#121 Reset links sent through email
  .env.example
  mailer/mailer.js
  package-lock.json
  package.json
  routes/user.js
  server.js
Labels: GSSoC22, Level2

#125 Reset password page designed
  client/src/ForgotPasswordPage/ResetPassword.css
  client/src/ForgotPasswordPage/ResetPassword.js
Labels: GSSoC22, Level3

#124 Frontend and backend connected for reset-password page
  client/src/App.js
  client/src/ForgotPasswordPage/ForgotPassword.js
  client/src/Login/Login.jsx
Labels: GSSoC22, Level2

#130 About us page created
  client/package-lock.json
  client/src/AboutusPage/AboutusPage.css
  client/src/AboutusPage/AboutusPage.js
  client/src/App.js
  client/src/HomePage/Navbar/Navbar.js
  client/src/assets/startuplife-amico.png
Labels: GSSoC22, Level2

#133 UserProductsDisplayed
  client/src/CreateProduct/CreateProduct.jsx
  client/src/CreateProduct/ProductItem.jsx
  client/src/utils/constants.js
  package-lock.json
  routes/project.js
Labels: GSSoC22, Level3

#131 ResetToken added and Schema modified
  client/src/App.js
  model/User.js
  routes/user.js
Labels: GSSoC22, Level3

#139 add a mobile nav
  client/src/App.css
  client/src/App.js
  client/src/Components/Product/Product.jsx
  client/src/HomePage/Navbar/Navbar.css
  client/src/HomePage/Navbar/Navbar.js
Labels: GSSoC22, Level3

#144 Reset password link getting expired in 20 min
  client/package-lock.json
  model/User.js
  package-lock.json
  routes/user.js
Labels: GSSoC22, Level2

#152 User is being navigated to homepage after signup
  client/src/Register/Register.jsx
Labels: GSSoC22, Level1

#142 NewPageForUserProducts
  client/src/App.js
  client/src/CreateProduct/CreateProduct.jsx
  client/src/CreateProduct/MyProducts.jsx
  client/src/CreateProduct/ProductItem.jsx
  client/src/HomePage/Navbar/Navbar.js
  routes/project.js
Labels: GSSoC22, Level3

#151 improved the UI of Logout button
  client/src/App.js
  client/src/HomePage/Navbar/Navbar.js
Labels: GSSoC22, Level2

#153 updated
  client/src/HomePage/Navbar/Navbar.js
Labels: GSSoC22, Level1

#155 UI of cards inside my products improved
  client/src/App.js
  client/src/CreateProduct/CreateProduct.css
  client/src/CreateProduct/CreateProduct.jsx
  client/src/CreateProduct/MyProducts.jsx
  client/src/CreateProduct/ProductItem.jsx
  client/src/HomePage/Body.jsx
  client/src/HomePage/Navbar/Navbar.css
  client/src/HomePage/Navbar/Navbar.js
  client/src/Login/Login.css
  client/src/Register/Register.css
Labels: GSSoC22, Level3

#156 Like button functionality added for comments
  client/src/Components/Product/CommentBlock.jsx
  client/src/Components/Product/CommentSection.jsx
  client/src/utils/constants.js
Labels: GSSoC22, Level3

#157 Message added
  client/src/CreateProduct/MyProducts.jsx
Labels: GSSoC22, Level1

#159 add new project button added
  client/src/CreateProduct/MyProducts.jsx
Labels: GSSoC22, Level2

#161 CommentInSchemaBackendRoute
  client/package-lock.json
  model/Project.js
  package-lock.json
  package.json
  routes/project.js
Labels: GSSoC22, Level3

#162 ImageValidatorAdded
  client/package-lock.json
  client/package.json
  client/src/CreateProduct/CreateProduct.jsx
Labels: GSSoC22, Level2

#164 ProductAddedResponseModified
  client/src/CreateProduct/CreateProduct.jsx
Labels: GSSoC22, Level2

#166 My Profile page added
  client/src/App.js
  client/src/MyProfile/MyProfile.css
  client/src/MyProfile/MyProfile.js
Labels: GSSoC22, Level3

#170 Projects fetched from database and displayed.
  client/src/Components/Product/ProductPreview.jsx
  client/src/CreateProduct/CreateProduct.css
  client/src/CreateProduct/CreateProduct.jsx
  client/src/HomePage/Body.jsx
  client/src/HomePage/Navbar/Navbar.css
  client/src/HomePage/Navbar/Navbar.js
  client/src/Login/Login.css
  client/src/Login/Login.jsx
  client/src/MyProfile/MyProfile.css
  client/src/MyProfile/MyProfile.js
  client/src/Register/Register.css
  client/src/Register/Register.jsx
  client/src/utils/constants.js
  routes/project.js
Labels: GSSoC22, Level3

#173 ButtonPositionFixed
  client/src/CreateProduct/CreateProduct.css
  client/src/CreateProduct/MyProducts.jsx
  client/src/HomePage/Footer.css
Labels: GSSoC22, Level2

#174 likes rendered with database and states too maintained
  client/src/Components/Product/ProductPreview.jsx
  client/src/CreateProduct/CreateProduct.jsx
  client/src/HomePage/Body.jsx
  client/src/utils/constants.js
  model/Project.js
  routes/project.js
Labels: GSSoC22, Level2

#179 Details of the project got displayed on click
  client/src/Components/Product/CommentSection.jsx
  client/src/Components/Product/Product.jsx
  client/src/Components/Product/ProductPreview.jsx
  client/src/HomePage/Body.jsx
  middleware/auth.js
  routes/project.js
Labels: GSSoC22, Level3

#186 User can not like more than once
  client/package-lock.json
  client/src/Components/Product/ProductPreview.jsx
  package-lock.json
  routes/project.js
  routes/user.js
Labels: GSSoC22, Level2

#185 Created a global Db using MongoDb atlas
  db/mongoose.js
Labels: GSSoC22, Level2

#188 corrected typo in my products page
  client/src/CreateProduct/MyProducts.jsx
Labels: GSSoC22, Level1

#189 My branch3
  client/src/Components/Product/CommentBlock.jsx
  client/src/Components/Product/CommentSection.jsx
  client/src/Components/Product/Product.jsx
  model/Project.js
  routes/project.js
Labels: GSSoC22, Level3

#191 Like button turns blue after liking
  client/src/Components/Product/ProductPreview.jsx
  client/src/HomePage/Body.jsx
  routes/user.js
Labels: GSSoC22, Level2

#195 NameAdded with card
  client/src/Components/Product/ProductPreview.jsx
  client/src/HomePage/Body.jsx
  db/mongoose.js
  model/Project.js
  package-lock.json
  routes/project.js
Labels: GSSoC22, Level2

#196 User details getting updated
  client/src/MyProfile/MyProfile.js
  routes/user.js
Labels: GSSoC22, Level3

#197 No of likes to the comment getting saved to database
  client/src/Components/Product/CommentBlock.jsx
  client/src/Components/Product/CommentSection.jsx
  client/src/Components/Product/Product.jsx
  model/Project.js
  routes/project.js
Labels: GSSoC22, Level2

#202 Comment with more likes are displayed first
  client/src/Components/Product/CommentSection.jsx
Labels: GSSoC22, Level3

#204 User has to login before liking comment
  client/src/Components/Product/CommentBlock.jsx
  client/src/Components/Product/ProductPreview.jsx
  middleware/auth.js
  routes/project.js
Labels: GSSoC22, Level2

#203 The profile page shows proper values instead of placeholders
  client/src/MyProfile/MyProfile.js
Labels: GSSoC22, Level3

#206 User can not like to any specific comment more than once.
  client/src/Components/Product/CommentBlock.jsx
  client/src/Components/Product/ProductPreview.jsx
  model/Project.js
  routes/project.js
Labels: GSSoC22, Level1

#211 Original description
  client/src/Components/Product/Description.jsx
  client/src/Components/Product/Product.jsx
Labels: GSSoC22, Level2
